# Generated by Django 5.0.14 on 2026-05-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmailDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender', models.CharField(max_length=255)),
                ('email_subject', models.CharField(max_length=500)),
                ('email_date', models.DateTimeField()),
                ('email_message_id', models.CharField(max_length=255, unique=True)),
                ('raw_email_snippet', models.TextField()),
                ('detected_service', models.CharField(max_length=100)),
                ('detected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detected_currency', models.CharField(default='USD', max_length=3)),
                ('detected_billing_cycle', models.CharField(blank=True, max_length=20)),
                ('detected_date', models.DateField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('detection_method', models.CharField(default='regex', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gmail_detection_gmaildetection',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('emails_scanned', models.PositiveIntegerField(default=0)),
                ('subscriptions_found', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'gmail_detection_scansession',
                'ordering': ['-started_at'],
            },
        ),
    ]
