# Generated by Django 5.0.14 on 2026-05-15 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gmail_detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(choices=[('tv', 'TV/Entertainment'), ('zap', 'Productivity'), ('book-open', 'Education'), ('dumbbell', 'Fitness'), ('cloud', 'Cloud Services'), ('credit-card', 'Finance'), ('music', 'Music'), ('gamepad-2', 'Gaming'), ('newspaper', 'News'), ('shopping-bag', 'Shopping'), ('heart-pulse', 'Health'), ('plane', 'Travel')], default='tv', max_length=20)),
                ('color', models.CharField(choices=[('#EF4444', 'Red'), ('#F97316', 'Orange'), ('#EAB308', 'Yellow'), ('#22C55E', 'Green'), ('#06B6D4', 'Cyan'), ('#3B82F6', 'Blue'), ('#6366F1', 'Indigo'), ('#8B5CF6', 'Purple'), ('#EC4899', 'Pink'), ('#14B8A6', 'Teal'), ('#F43F5E', 'Rose')], default='#3B82F6', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'subscriptions_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='subscription_logos/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', '$ - US Dollar'), ('EUR', '€ - Euro'), ('GBP', '£ - British Pound'), ('INR', '₹ - Indian Rupee'), ('JPY', '¥ - Japanese Yen'), ('CAD', 'C$ - Canadian Dollar'), ('AUD', 'A$ - Australian Dollar')], default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=20)),
                ('renewal_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('started_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('expired', 'Expired')], default='active', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], default='credit_card', max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.category')),
                ('gmail_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='gmail_detection.gmaildetection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_subscription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'subscriptions_subscriptionhistory',
                'ordering': ['-created_at'],
            },
        ),
    ]
